version: '3.8'

services:
  aimc-minedojo:
    image: aimc-minedojo:latest
    platform: linux/amd64
    container_name: aimc-minedojo
    
    # 挂载项目目录
    volumes:
      - ..:/workspace
      
    # 保持容器运行
    stdin_open: true
    tty: true
    
    # 环境变量
    environment:
      - JAVA_OPTS=-Djava.awt.headless=true
      - DISPLAY=:0
    
    # 共享内存大小（MineDojo 可能需要）
    shm_size: '2gb'
    
    # 网络模式
    network_mode: bridge
    
    # 工作目录
    working_dir: /workspace
    
    # 启动命令
    command: /bin/bash

