version: '3.8'

services:
  minedojo:
    build:
      context: .
      dockerfile: Dockerfile.arm64
      platforms:
        - linux/arm64
    image: minedojo-macos:latest
    platform: linux/arm64
    container_name: minedojo-dev
    
    # 挂载项目目录
    volumes:
      - ..:/workspace
    
    # 环境变量
    environment:
      - DISPLAY=:99
      - JAVA_OPTS=-Djava.awt.headless=true
      - MAVEN_OPTS=-Djava.awt.headless=true
      - PYTHONUNBUFFERED=1
    
    # 工作目录
    working_dir: /workspace
    
    # 保持容器运行，允许交互
    stdin_open: true
    tty: true
    
    # 端口映射（用于 Jupyter 等）
    ports:
      - "8888:8888"  # Jupyter
      - "6006:6006"  # TensorBoard

