# MineDojo harvest_1_paper 训练配置文件
# 可以通过修改这个文件来调整训练参数

# ============================================================================
# 任务配置
# ============================================================================
task:
  task_id: "harvest_milk"  # 任务ID (harvest_milk 更稳定，可改为 harvest_1_paper)
  image_size: [160, 256]   # 图像尺寸 [height, width]
  max_episode_steps: 2000  # 每个episode最大步数

# ============================================================================
# 训练配置
# ============================================================================
training:
  total_timesteps: 500000  # 总训练步数 (建议: 500K-2M)
  n_envs: 1                # 并行环境数 (增加可加速训练，但需要更多内存)
  device: "auto"           # 设备: auto/cpu/cuda
  
  # PPO超参数
  ppo:
    learning_rate: 0.0003  # 学习率
    n_steps: 2048          # 每次更新收集的步数
    batch_size: 64         # 批次大小
    n_epochs: 10           # 每次更新的epoch数
    gamma: 0.99            # 折扣因子
    gae_lambda: 0.95       # GAE lambda
    clip_range: 0.2        # PPO裁剪范围
    ent_coef: 0.01         # 熵系数（鼓励探索）
    vf_coef: 0.5           # 价值函数损失系数
    max_grad_norm: 0.5     # 梯度裁剪阈值

# ============================================================================
# 保存和评估
# ============================================================================
checkpointing:
  save_freq: 10000           # 保存检查点的步数间隔
  checkpoint_dir: "checkpoints/harvest_paper"
  
evaluation:
  eval_freq: 10000           # 评估的步数间隔
  n_eval_episodes: 5         # 每次评估运行的episode数
  
logging:
  log_dir: "logs/training"
  tensorboard_dir: "logs/tensorboard"

# ============================================================================
# 环境包装器配置
# ============================================================================
env_wrapper:
  use_frame_stack: false     # 是否使用帧堆叠
  frame_stack_n: 4           # 堆叠帧数
  use_discrete_actions: true # 是否使用离散动作空间

# ============================================================================
# 训练场景配置（根据硬件选择）
# ============================================================================
# 快速测试配置（用于验证代码）
quick_test:
  total_timesteps: 10000
  save_freq: 5000
  eval_freq: 5000
  n_envs: 1

# 标准训练配置（推荐）
standard:
  total_timesteps: 500000
  save_freq: 10000
  eval_freq: 10000
  n_envs: 1

# 高性能配置（多GPU/CPU）
high_performance:
  total_timesteps: 2000000
  save_freq: 20000
  eval_freq: 20000
  n_envs: 4
  batch_size: 128

# ============================================================================
# 注意事项
# ============================================================================
# 1. 训练是从头开始的，没有预训练权重
# 2. harvest_milk 比 harvest_1_paper 更容易，建议先用它测试
# 3. 增加 n_envs 可以加速训练，但需要更多内存
# 4. 调整 ent_coef 可以控制探索程度（值越大探索越多）
# 5. 建议先用 quick_test 配置验证代码正确性

